### ISSUE TITLE
incompatible plugin with version 4.13

### ISSUE THREAD

**Issue by legitscoper** [Ikarus76/UEJoystickPlugin#13]
Plugin is incompatible. Is there any way to recompile it?

**Comment by tsky1971** [comment]
You may use this https://github.com/tsky1971/UEJoystickPlugin or this https://github.com/samiljan/UEJoystickPlugin
if you only want have access to joystick. Normally i try to be updated in my repo. to be compatible.
t.

**Comment by legitscoper** [comment]
thx
